- name: Ensure base mount directory exists
  file:
    path: "{{ rancher_data_dir | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure Docker and Rancher directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0711'
  loop:
    - "{{ docker_data_root }}"
    - "{{ rancher_data_dir }}"
