---
- name: Validate sudoers file for {{ item.name }}
  command: "visudo -cf /etc/sudoers.d/{{ item.name }}"
  become: true

- name: Restart sshd
  service:
    name: "{{ 'sshd' if ansible_facts['os_family'] == 'RedHat' else 'ssh' }}"
    state: restarted
  become: true
