---
- name: Reboot Cluster Nodes
  hosts: kube_control_plane:kube_node
  become: true
  serial: 1
  tasks:
    - name: Reboot node
      ansible.builtin.reboot:
        reboot_timeout: 300
        msg: "Rebooting for Cilium Gateway API networking changes"
