galaxy_info:
  author: "example_tenant"
  description: "Canonical Landscape server installation"
  company: "example_tenant"
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies: []